### ISSUE TITLE
In the How it works section, did you mean node-ping repo to be cloned instead of node-monitor?

### ISSUE THREAD

**Issue by DivyaYash** [qawemlilo/node-ping#2]

**Comment by DivyaYash** [comment]
I went ahead and cloned the node-ping repo, and followed the instructions..Says cannot fine ping-monitor module..
node app
module.js:338
    throw err;
          ^
Error: Cannot find module 'ping-monitor'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/node-ping/node-ping/app.js:2:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by qawemlilo** [comment]
Sorry the docs need to be updated. Do the following.

`git clone https://github.com/qawemlilo/node-ping.git`

**Comment by qawemlilo** [comment]
I think Google has changed the way apps can send emails through the Gmail API - please refer to the [Node Mailer](https://github.com/andris9/Nodemailer) docs if you run into issues.

**Comment by DivyaYash** [comment]
I see the below error - Is this related to mail feature? I really do not have any knowledge around this area, just came across your tool and giving it a try :)
node app
module.js:338
    throw err;
          ^
Error: Cannot find module 'ping-monitor'

**Comment by qawemlilo** [comment]
@DivyaYash did you run the `npm install` command? you need that to install dependencies.

**Comment by DivyaYash** [comment]
oh, :) ran it now, please tolerate me! Should I expect a mail if a URL goes down? Also, where can i set the poling interval? This is what I see now..
Monitoring: http://yyy/index.html/
Time: 2015-12-10 20:06:10


Monitoring: http://xxx/login.html
Time: 2015-12-10 20:06:10

Listening to port 3008

**Comment by qawemlilo** [comment]
You can set the polling interval in `websites.json`. 

Example

```
...
  {
    "url": "http://www.bookmarkmanager.co.za",
    "timeout": "15" <---- polling every 15 mins
  },
...
```

**Comment by qawemlilo** [comment]
I will test the mailing part and update the docs tomorrow.

**Comment by DivyaYash** [comment]
Ok, thank u very much! I dint realize timeout meant polling interval, thanks!
btw, I got the "Failed to send email" on the console..It would be helpful if we could send mail from the local smtp server via the sendmail/mail command..
Appreciate your prompt and quick response!

**Comment by qawemlilo** [comment]
@DivyaYash I have updated the code and docs, the best thing to do is delete the old repo and download afresh. If you continue to experience problems with receiving emails please visit the [nodemailer](https://github.com/andris9/Nodemailer) project for further details.

**Comment by DivyaYash** [comment]
@qawemlilo thanku, I notice that the config.json now has only one line as email, unlike previous one. Is this the mail id to which the alert mails would be sent to? Plz confirm..

**Comment by qawemlilo** [comment]
Yes

**Comment by DivyaYash** [comment]
Ok..Failed to send email. undefined - I got this...will try to read through node mailer as you suggested..
So, where is the config for which service it uses now? Since I have no developer background, could not understand mailer.js much..

**Comment by qawemlilo** [comment]
Sorry this is targeted at people with a bit of programming skills, if you follow the links I provided you with you will find the solution.

**Comment by DivyaYash** [comment]
Ok, thank u, will reach out for my developer friends and see if I can get the mailing to work..
Thanks again!
